import { router, useLocalSearchParams } from 'expo-router';
import React, { useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';
import { ChoiceChips, Field, Header, PrimaryButton, Screen } from '@/components/GymUI';
import { useGym } from '@/context/GymContext';
import { PaymentMethod, formatRs } from '@/lib/gymos-data';
import { useColors } from '@/hooks/useColors';

export default function NewPayment() {
  const colors = useColors(); const { data, addPayment, updateMember } = useGym(); const params = useLocalSearchParams<{ memberId?: string; renew?: string }>(); const [memberId, setMemberId] = useState(params.memberId ?? ''); const [planId, setPlanId] = useState(data.plans[0]?.id ?? ''); const [method, setMethod] = useState<PaymentMethod>('Cash'); const [notes, setNotes] = useState('');
  const member = data.members.find((item) => item.id === memberId); const plan = data.plans.find((item) => item.id === planId);
  const save = async () => { if (!member || !plan) { Alert.alert('Select a member and plan', 'A full payment must be linked to a member and membership plan.'); return; } const start = new Date(); const end = new Date(); end.setDate(end.getDate() + plan.durationDays); const payment = await addPayment({ memberId: member.id, membershipId: member.membership?.id, amount: plan.price, method, date: new Date().toISOString(), notes }); await updateMember(member.id, { membership: { id: member.membership?.id ?? `membership_${Date.now()}`, planId: plan.id, startDate: start.toISOString(), endDate: end.toISOString() } }); router.replace({ pathname: '/payment/success', params: { paymentId: payment.id } }); };
  return <Screen><Header title={params.renew ? 'Renew membership' : 'Record payment'} subtitle="Full payment only" onBack={() => router.back()} /><KeyboardAwareScrollViewCompat contentContainerStyle={styles.content}><View style={[styles.rule, { backgroundColor: colors.secondary }]}><Text style={[styles.ruleTitle, { color: colors.secondaryForeground }]}>No partial payments</Text><Text style={[styles.ruleBody, { color: colors.mutedForeground }]}>GymOS records completed membership payments only. No installments or remaining balances.</Text></View><Text style={[styles.label, { color: colors.mutedForeground }]}>MEMBER</Text><ChoiceChips options={data.members.filter((item) => !item.archived).map((item) => item.name)} selected={member?.name ?? 'Select member'} onSelect={(value) => setMemberId(data.members.find((item) => item.name === value)?.id ?? '')} /><Text style={[styles.label, { color: colors.mutedForeground }]}>MEMBERSHIP PLAN</Text><ChoiceChips options={data.plans.filter((item) => item.active).map((item) => item.name)} selected={plan?.name ?? ''} onSelect={(value) => setPlanId(data.plans.find((item) => item.name === value)?.id ?? '')} />{plan ? <View style={[styles.amount, { backgroundColor: colors.primary }]}><Text style={[styles.amountLabel, { color: '#B9C6BC' }]}>FULL AMOUNT DUE</Text><Text style={[styles.amountValue, { color: colors.accent }]}>{formatRs(plan.price)}</Text><Text style={[styles.amountMeta, { color: '#B9C6BC' }]}>{plan.durationDays} days · {plan.name} membership</Text></View> : null}<Text style={[styles.label, { color: colors.mutedForeground }]}>PAYMENT METHOD</Text><ChoiceChips options={['Cash', 'Easypaisa', 'JazzCash', 'Bank Transfer', 'Card']} selected={method} onSelect={(value) => setMethod(value as PaymentMethod)} /><Field label="Notes" value={notes} onChangeText={setNotes} placeholder="Optional note" /><PrimaryButton title={params.renew ? 'Renew & record payment' : 'Record full payment'} icon="check-circle" onPress={save} /></KeyboardAwareScrollViewCompat></Screen>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 45 }, rule: { borderRadius: 16, padding: 14, marginBottom: 22 }, ruleTitle: { fontFamily: 'Inter_700Bold', fontSize: 13 }, ruleBody: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 17, marginTop: 4 }, label: { fontFamily: 'Inter_600SemiBold', fontSize: 11, letterSpacing: 0.5, marginBottom: 8, marginTop: 9 }, amount: { borderRadius: 19, padding: 18, marginVertical: 20 }, amountLabel: { fontFamily: 'Inter_600SemiBold', fontSize: 10, letterSpacing: 1 }, amountValue: { fontFamily: 'Inter_700Bold', fontSize: 30, marginTop: 6 }, amountMeta: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 } });