import { Feather } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Header, PrimaryButton, ScreenScroll } from '@/components/GymUI';
import { useGym } from '@/context/GymContext';
import { formatDate, formatRs } from '@/lib/gymos-data';
import { useColors } from '@/hooks/useColors';

export default function PaymentSuccess() {
  const colors = useColors(); const { paymentId } = useLocalSearchParams<{ paymentId: string }>(); const { data } = useGym(); const payment = data.payments.find((item) => item.id === paymentId); const member = data.members.find((item) => item.id === payment?.memberId);
  return <ScreenScroll><Header title="Payment receipt" /><View style={styles.success}><View style={[styles.check, { backgroundColor: colors.accent }]}><Feather name="check" size={30} color={colors.foreground} /></View><Text style={[styles.successTitle, { color: colors.foreground }]}>Payment successful</Text><Text style={[styles.successBody, { color: colors.mutedForeground }]}>The membership is active and the receipt is ready.</Text></View>{payment ? <View style={[styles.receipt, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.receiptTop}><View><Text style={[styles.receiptLabel, { color: colors.mutedForeground }]}>RECEIPT NUMBER</Text><Text style={[styles.receiptNumber, { color: colors.foreground }]}>{payment.receiptNumber}</Text></View><Feather name="file-text" size={22} color={colors.mutedForeground} /></View><Row label="Member" value={member?.name ?? 'Member'} /><Row label="Amount" value={formatRs(payment.amount)} /><Row label="Method" value={payment.method} /><Row label="Date" value={formatDate(payment.date, true)} /></View> : null}<View style={styles.buttons}><PrimaryButton title="Done" icon="arrow-right" onPress={() => router.replace('/(tabs)')} /><Pressable onPress={() => undefined} style={styles.share}><Feather name="share-2" size={16} color={colors.secondaryForeground} /><Text style={[styles.shareText, { color: colors.secondaryForeground }]}>Share receipt</Text></Pressable></View></ScreenScroll>;
}
function Row({ label, value }: { label: string; value: string }) { const colors = useColors(); return <View style={styles.row}><Text style={[styles.label, { color: colors.mutedForeground }]}>{label}</Text><Text style={[styles.value, { color: colors.foreground }]}>{value}</Text></View>; }
const styles = StyleSheet.create({ success: { alignItems: 'center', paddingVertical: 24 }, check: { width: 68, height: 68, borderRadius: 24, alignItems: 'center', justifyContent: 'center' }, successTitle: { fontFamily: 'Inter_700Bold', fontSize: 22, marginTop: 17 }, successBody: { fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 6 }, receipt: { borderWidth: 1, borderRadius: 20, padding: 17 }, receiptTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 13 }, receiptLabel: { fontFamily: 'Inter_600SemiBold', fontSize: 10, letterSpacing: 0.8 }, receiptNumber: { fontFamily: 'Inter_700Bold', fontSize: 18, marginTop: 5 }, row: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: 'rgba(128,128,128,0.12)', paddingVertical: 12 }, label: { fontFamily: 'Inter_500Medium', fontSize: 12 }, value: { fontFamily: 'Inter_600SemiBold', fontSize: 12 }, buttons: { marginTop: 18, gap: 14 }, share: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 7, padding: 10 }, shareText: { fontFamily: 'Inter_600SemiBold', fontSize: 12 } });