import { router } from 'expo-router';
import React, { useState } from 'react';
import { Alert, StyleSheet, Text } from 'react-native';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';
import { ChoiceChips, Field, Header, PrimaryButton, Screen, SectionTitle } from '@/components/GymUI';
import { useColors } from '@/hooks/useColors';
import { useGym } from '@/context/GymContext';
import { iso } from '@/lib/gymos-data';

export default function NewMember() {
  const colors = useColors();
  const { data, addMember } = useGym();
  const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [gender, setGender] = useState('Female'); const [dob, setDob] = useState(''); const [address, setAddress] = useState(''); const [emergency, setEmergency] = useState(''); const [planId, setPlanId] = useState(data.plans[0]?.id ?? ''); const [trainerId, setTrainerId] = useState(''); const [notes, setNotes] = useState('');
  const save = async () => { if (!name.trim() || phone.trim().length < 7) { Alert.alert('Complete the profile', 'Add the member name and a valid phone number.'); return; } const plan = data.plans.find((item) => item.id === planId); const start = new Date(); const end = new Date(); end.setDate(end.getDate() + (plan?.durationDays ?? 30)); const member = await addMember({ name: name.trim(), phone: phone.trim(), gender, dob: dob || iso(-7300), address, emergencyContact: emergency, joinDate: start.toISOString(), trainerId: trainerId || undefined, notes, archived: false, membership: plan ? { id: `membership_${Date.now()}`, planId, startDate: start.toISOString(), endDate: end.toISOString() } : undefined }); router.replace({ pathname: '/member/[id]', params: { id: member.id, created: '1' } }); };
  return <Screen><Header title="Add member" subtitle="Create a new gym profile" onBack={() => router.back()} /><KeyboardAwareScrollViewCompat contentContainerStyle={styles.content}><Text style={[styles.intro, { color: colors.mutedForeground }]}>A strong profile helps your team deliver a better experience at every visit.</Text><SectionTitle title="Personal information" /><Field label="Full name *" value={name} onChangeText={setName} placeholder="e.g. Amna Khalid" /><Field label="Phone number *" value={phone} onChangeText={setPhone} placeholder="03xx xxxxxxx" keyboardType="phone-pad" /><Text style={[styles.label, { color: colors.mutedForeground }]}>GENDER</Text><ChoiceChips options={['Female', 'Male', 'Prefer not to say']} selected={gender} onSelect={setGender} /><Field label="Date of birth" value={dob} onChangeText={setDob} placeholder="DD / MM / YYYY" /><Field label="Address" value={address} onChangeText={setAddress} placeholder="Street, area, city" /><Field label="Emergency contact" value={emergency} onChangeText={setEmergency} placeholder="Name and phone" /><SectionTitle title="Gym setup" /><Text style={[styles.label, { color: colors.mutedForeground }]}>MEMBERSHIP PLAN</Text><ChoiceChips options={data.plans.filter((plan) => plan.active).map((plan) => plan.name)} selected={data.plans.find((plan) => plan.id === planId)?.name ?? ''} onSelect={(value) => setPlanId(data.plans.find((plan) => plan.name === value)?.id ?? '')} /><Text style={[styles.helper, { color: colors.mutedForeground }]}>Start date is today. You can activate the member by recording their full payment after saving.</Text><Text style={[styles.label, { color: colors.mutedForeground }]}>ASSIGNED TRAINER</Text><ChoiceChips options={['No trainer', ...data.trainers.map((trainer) => trainer.name)]} selected={data.trainers.find((trainer) => trainer.id === trainerId)?.name ?? 'No trainer'} onSelect={(value) => setTrainerId(data.trainers.find((trainer) => trainer.name === value)?.id ?? '')} /><Field label="Notes" value={notes} onChangeText={setNotes} placeholder="Preferences, goals or context" multiline style={styles.notes} /><PrimaryButton title="Save member" icon="check" onPress={save} /></KeyboardAwareScrollViewCompat></Screen>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 40 }, intro: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 21 }, label: { fontFamily: 'Inter_600SemiBold', fontSize: 11, letterSpacing: 0.5, marginBottom: 8, marginTop: 4 }, helper: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 17, marginVertical: 11 }, notes: { height: 84, paddingTop: 13, textAlignVertical: 'top' } });