import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useGym } from '@/context/GymContext';
import { ChoiceChips, EmptyState, Header, ScreenScroll, SearchField } from '@/components/GymUI';
import { formatDate, formatRs } from '@/lib/gymos-data';
import { useColors } from '@/hooks/useColors';

export default function Payments() {
  const colors = useColors(); const { data, voidPayment } = useGym(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All');
  const payments = useMemo(() => data.payments.filter((payment) => { const member = data.members.find((item) => item.id === payment.memberId); const matches = `${member?.name ?? ''} ${payment.receiptNumber} ${payment.transactionId}`.toLowerCase().includes(query.toLowerCase()); return matches && (filter === 'All' || payment.method === filter); }), [data.members, data.payments, filter, query]);
  const validTotal = data.payments.filter((payment) => payment.status === 'completed').reduce((sum, payment) => sum + payment.amount, 0);
  return <ScreenScroll><Header title="Payments" subtitle={`${formatRs(validTotal)} valid revenue`} right={<Pressable onPress={() => router.push('/payment/new')} style={[styles.add, { backgroundColor: colors.primary }]}><Feather name="plus" size={19} color={colors.primaryForeground} /></Pressable>} /><SearchField value={query} onChangeText={setQuery} placeholder="Search member or receipt" /><View style={styles.filters}><ChoiceChips options={['All', 'Cash', 'Easypaisa', 'JazzCash', 'Card']} selected={filter} onSelect={setFilter} /></View>{payments.length ? payments.map((payment) => { const member = data.members.find((item) => item.id === payment.memberId); return <Pressable key={payment.id} onLongPress={() => payment.status === 'completed' && Alert.alert('Void payment?', `${payment.receiptNumber} will remain in the audit history and stop counting toward revenue.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Void payment', style: 'destructive', onPress: () => voidPayment(payment.id, 'Voided from payments list') }])} onPress={() => member && router.push({ pathname: '/member/[id]', params: { id: member.id } })} style={[styles.payment, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.method, { backgroundColor: payment.status === 'voided' ? colors.muted : colors.secondary }]}><Feather name={payment.status === 'voided' ? 'slash' : 'credit-card'} size={17} color={payment.status === 'voided' ? colors.mutedForeground : colors.secondaryForeground} /></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{member?.name ?? 'Unknown member'}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{payment.receiptNumber} · {payment.method} · {formatDate(payment.date)}</Text></View><View style={styles.amount}><Text style={[styles.amountText, { color: payment.status === 'voided' ? colors.mutedForeground : colors.foreground, textDecorationLine: payment.status === 'voided' ? 'line-through' : 'none' }]}>{formatRs(payment.amount)}</Text>{payment.status === 'voided' ? <Text style={[styles.voided, { color: colors.destructive }]}>VOIDED</Text> : null}</View></Pressable>}) : <EmptyState icon="credit-card" title="No payments found" body="Payments you record will appear here with their receipts." />}<Text style={[styles.hint, { color: colors.mutedForeground }]}>Tip: long press a valid payment to void it. Voided records are preserved and excluded from reports.</Text></ScreenScroll>;
}
const styles = StyleSheet.create({ add: { width: 38, height: 38, borderRadius: 13, justifyContent: 'center', alignItems: 'center' }, filters: { marginTop: 14, marginBottom: 15 }, payment: { borderWidth: 1, borderRadius: 16, padding: 11, flexDirection: 'row', gap: 11, alignItems: 'center', marginBottom: 8 }, method: { width: 38, height: 38, borderRadius: 13, justifyContent: 'center', alignItems: 'center' }, name: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, meta: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 4 }, amount: { alignItems: 'flex-end' }, amountText: { fontFamily: 'Inter_700Bold', fontSize: 13 }, voided: { fontFamily: 'Inter_700Bold', fontSize: 8, marginTop: 3 }, hint: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 17, marginTop: 11, textAlign: 'center' } });