import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useGym } from '@/context/GymContext';
import { ChoiceChips, Field, Header, PrimaryButton, ScreenScroll } from '@/components/GymUI';
import { formatRs } from '@/lib/gymos-data';
import { useColors } from '@/hooks/useColors';

export default function Plans() {
  const colors = useColors(); const { data, addPlan, togglePlan } = useGym(); const [adding, setAdding] = useState(false); const [name, setName] = useState(''); const [price, setPrice] = useState(''); const [days, setDays] = useState('30');
  const save = () => { if (!name.trim() || !Number(price) || !Number(days)) { Alert.alert('Complete plan details', 'Add a name, price and duration.'); return; } addPlan({ name: name.trim(), price: Number(price), durationDays: Number(days), active: true }); setName(''); setPrice(''); setDays('30'); setAdding(false); };
  return <ScreenScroll><Header title="Membership plans" subtitle={`${data.plans.filter((plan) => plan.active).length} active plans`} right={<Pressable onPress={() => setAdding(!adding)} style={[styles.add, { backgroundColor: colors.primary }]}><Feather name={adding ? 'x' : 'plus'} size={19} color={colors.primaryForeground} /></Pressable>} />{adding ? <View style={[styles.form, { backgroundColor: colors.card, borderColor: colors.border }]}><Field label="Plan name" value={name} onChangeText={setName} placeholder="e.g. Student" /><Field label="Price (PKR)" value={price} onChangeText={setPrice} placeholder="5000" keyboardType="number-pad" /><Text style={[styles.label, { color: colors.mutedForeground }]}>DURATION</Text><ChoiceChips options={['30', '90', '180', '365']} selected={days} onSelect={setDays} /><PrimaryButton title="Create plan" icon="check" onPress={save} /></View> : null}{data.plans.map((plan) => <View key={plan.id} style={[styles.plan, { backgroundColor: colors.card, borderColor: colors.border, opacity: plan.active ? 1 : 0.58 }]}><View style={[styles.planIcon, { backgroundColor: plan.active ? colors.accent : colors.muted }]}><Feather name="layers" size={18} color={colors.foreground} /></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{plan.name}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{plan.durationDays} days · {plan.active ? 'Available for new members' : 'Archived'}</Text></View><View style={styles.price}><Text style={[styles.priceText, { color: colors.foreground }]}>{formatRs(plan.price)}</Text><Pressable onPress={() => togglePlan(plan.id)}><Text style={[styles.archive, { color: plan.active ? colors.destructive : colors.secondaryForeground }]}>{plan.active ? 'Archive' : 'Restore'}</Text></Pressable></View></View>)}<View style={[styles.note, { backgroundColor: colors.secondary }]}><Feather name="info" size={16} color={colors.secondaryForeground} /><Text style={[styles.noteText, { color: colors.mutedForeground }]}>Plans with active members are archived rather than deleted, so history always remains safe.</Text></View></ScreenScroll>;
}
const styles = StyleSheet.create({ add: { width: 38, height: 38, borderRadius: 13, justifyContent: 'center', alignItems: 'center' }, form: { borderWidth: 1, borderRadius: 18, padding: 15, marginBottom: 14 }, label: { fontFamily: 'Inter_600SemiBold', fontSize: 11, letterSpacing: 0.5, marginBottom: 8 }, plan: { borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 9 }, planIcon: { width: 40, height: 40, borderRadius: 14, justifyContent: 'center', alignItems: 'center' }, name: { fontFamily: 'Inter_700Bold', fontSize: 14 }, meta: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 4 }, price: { alignItems: 'flex-end' }, priceText: { fontFamily: 'Inter_700Bold', fontSize: 14 }, archive: { fontFamily: 'Inter_600SemiBold', fontSize: 10, marginTop: 5 }, note: { padding: 13, borderRadius: 15, flexDirection: 'row', gap: 9, marginTop: 8 }, noteText: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 17, flex: 1 } });