import { Feather } from '@expo/vector-icons';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useGym } from '@/context/GymContext';
import { formatRs, memberStatus } from '@/lib/gymos-data';
import { Header, ScreenScroll, SectionTitle, StatCard } from '@/components/GymUI';
import { useColors } from '@/hooks/useColors';

export default function Reports() {
  const colors = useColors(); const { data } = useGym(); const valid = data.payments.filter((payment) => payment.status === 'completed'); const revenue = valid.reduce((sum, payment) => sum + payment.amount, 0); const active = data.members.filter((member) => memberStatus(member) === 'Active').length; const today = new Date().toDateString(); const visitsToday = data.attendance.filter((item) => new Date(item.checkIn).toDateString() === today).length; const methods = ['Cash', 'Easypaisa', 'JazzCash', 'Bank Transfer', 'Card'].map((method) => ({ method, value: valid.filter((payment) => payment.method === method).reduce((sum, payment) => sum + payment.amount, 0) })).filter((item) => item.value > 0);
  return <ScreenScroll><Header title="Reports" subtitle="A clear view of gym performance" /><View style={styles.hero}><Text style={[styles.eyebrow, { color: colors.accent }]}>ALL-TIME VALID REVENUE</Text><Text style={[styles.heroValue, { color: colors.primaryForeground }]}>{formatRs(revenue)}</Text><Text style={[styles.heroMeta, { color: '#B9C6BC' }]}>{valid.length} completed payments · voided excluded</Text></View><SectionTitle title="At a glance" /><View style={styles.grid}><View style={styles.column}><StatCard label="Active members" value={active} icon="users" /><StatCard label="Today’s visits" value={visitsToday} icon="check-circle" /></View><View style={styles.column}><StatCard label="Expiring soon" value={data.members.filter((m) => memberStatus(m) === 'Expiring Soon').length} icon="clock" accent /><StatCard label="Total members" value={data.members.filter((m) => !m.archived).length} icon="user" /></View></View><SectionTitle title="Payment methods" /><View style={[styles.breakdown, { backgroundColor: colors.card, borderColor: colors.border }]}>{methods.map((item, index) => <View key={item.method} style={styles.methodRow}><View style={[styles.methodDot, { backgroundColor: [colors.accent, '#8BC4A8', '#E4B86A', '#7FA7D8', '#D18CB9'][index] }]} /><Text style={[styles.methodName, { color: colors.foreground }]}>{item.method}</Text><Text style={[styles.methodValue, { color: colors.foreground }]}>{formatRs(item.value)}</Text></View>)}</View><SectionTitle title="Membership health" /><View style={[styles.health, { backgroundColor: colors.card, borderColor: colors.border }]}><Health label="Active" value={active} total={data.members.length} color={colors.secondaryForeground} /><Health label="Expiring soon" value={data.members.filter((m) => memberStatus(m) === 'Expiring Soon').length} total={data.members.length} color="#B78329" /><Health label="Expired" value={data.members.filter((m) => memberStatus(m) === 'Expired').length} total={data.members.length} color={colors.destructive} /></View></ScreenScroll>;
}
function Health({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { const colors = useColors(); return <View style={styles.healthRow}><View style={styles.healthTop}><Text style={[styles.methodName, { color: colors.foreground }]}>{label}</Text><Text style={[styles.methodValue, { color }]}>{value}</Text></View><View style={[styles.track, { backgroundColor: colors.muted }]}><View style={[styles.bar, { backgroundColor: color, width: `${Math.min((value / Math.max(total, 1)) * 100, 100)}%` }]} /></View></View>; }
const styles = StyleSheet.create({ hero: { borderRadius: 21, backgroundColor: '#17201B', padding: 20 }, eyebrow: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1 }, heroValue: { fontFamily: 'Inter_700Bold', fontSize: 31, marginTop: 9 }, heroMeta: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, grid: { flexDirection: 'row', gap: 10 }, column: { flex: 1, gap: 10 }, breakdown: { borderWidth: 1, borderRadius: 18, padding: 15 }, methodRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 7, gap: 8 }, methodDot: { width: 9, height: 9, borderRadius: 5 }, methodName: { fontFamily: 'Inter_500Medium', fontSize: 12, flex: 1 }, methodValue: { fontFamily: 'Inter_700Bold', fontSize: 12 }, health: { borderWidth: 1, borderRadius: 18, padding: 15, gap: 15 }, healthRow: { gap: 7 }, healthTop: { flexDirection: 'row', justifyContent: 'space-between' }, track: { height: 7, borderRadius: 4, overflow: 'hidden' }, bar: { height: 7, borderRadius: 4 } });