import { Feather } from '@expo/vector-icons';
import React from 'react';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useGym } from '@/context/GymContext';
import { Field, Header, PrimaryButton, ScreenScroll, SectionTitle } from '@/components/GymUI';
import { useColors } from '@/hooks/useColors';

export default function Settings() {
  const colors = useColors(); const { data, updateSettings } = useGym(); const [name, setName] = React.useState(data.settings.name); const [phone, setPhone] = React.useState(data.settings.phone); const [address, setAddress] = React.useState(data.settings.address);
  return <ScreenScroll><Header title="Settings" subtitle="Make GymOS fit your day" /><SectionTitle title="Gym profile" /><Field label="Gym name" value={name} onChangeText={setName} /><Field label="Phone number" value={phone} onChangeText={setPhone} keyboardType="phone-pad" /><Field label="Address" value={address} onChangeText={setAddress} /><PrimaryButton title="Save gym profile" icon="check" onPress={() => { updateSettings({ name, phone, address }); Alert.alert('Saved', 'Your gym profile has been updated.'); }} /><SectionTitle title="Preferences" /><ToggleRow icon="bell" title="Expiry reminders" body="Keep expiring memberships visible on your dashboard." value={data.settings.expiryReminders} onValueChange={(value) => updateSettings({ expiryReminders: value })} /><ToggleRow icon="log-in" title="Allow expired check-ins" body="When off, expired members must renew before entry." value={data.settings.allowExpiredCheckIn} onValueChange={(value) => updateSettings({ allowExpiredCheckIn: value })} /><SectionTitle title="Attendance hardware" /><View style={[styles.device, { backgroundColor: colors.secondary }]}><View style={[styles.deviceIcon, { backgroundColor: colors.accent }]}><Feather name="shield" size={18} color={colors.foreground} /></View><View style={{ flex: 1 }}><Text style={[styles.deviceTitle, { color: colors.foreground }]}>Biometric device</Text><Text style={[styles.deviceBody, { color: colors.mutedForeground }]}>Hardware not connected</Text></View><Text style={[styles.status, { color: colors.mutedForeground }]}>Future</Text></View><SectionTitle title="Account" /><Pressable onPress={() => Alert.alert('Change password', 'Password recovery will be connected when authentication is enabled.')} style={styles.link}><Feather name="lock" size={17} color={colors.mutedForeground} /><Text style={[styles.linkText, { color: colors.foreground }]}>Change password</Text><Feather name="chevron-right" size={16} color={colors.mutedForeground} /></Pressable><Pressable onPress={() => router.replace('/(tabs)')} style={styles.link}><Feather name="log-out" size={17} color={colors.destructive} /><Text style={[styles.linkText, { color: colors.destructive }]}>Log out</Text></Pressable></ScreenScroll>;
}
function ToggleRow({ icon, title, body, value, onValueChange }: { icon: keyof typeof Feather.glyphMap; title: string; body: string; value: boolean; onValueChange: (value: boolean) => void }) { const colors = useColors(); return <View style={styles.toggle}><View style={[styles.toggleIcon, { backgroundColor: colors.secondary }]}><Feather name={icon} size={16} color={colors.secondaryForeground} /></View><View style={{ flex: 1 }}><Text style={[styles.toggleTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.toggleBody, { color: colors.mutedForeground }]}>{body}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{ false: colors.border, true: colors.primary }} thumbColor={value ? colors.accent : colors.card} /></View>; }
const styles = StyleSheet.create({ device: { borderRadius: 17, padding: 13, flexDirection: 'row', gap: 10, alignItems: 'center' }, deviceIcon: { width: 37, height: 37, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, deviceTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, deviceBody: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, status: { fontFamily: 'Inter_600SemiBold', fontSize: 10 }, toggle: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 13 }, toggleIcon: { width: 35, height: 35, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, toggleTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, toggleBody: { fontFamily: 'Inter_400Regular', fontSize: 10, lineHeight: 15, marginTop: 3 }, link: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: 'rgba(128,128,128,0.14)' }, linkText: { fontFamily: 'Inter_600SemiBold', fontSize: 13, flex: 1 } });