import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useGym } from '@/context/GymContext';
import { Header, ScreenScroll, SectionTitle } from '@/components/GymUI';
import { useColors } from '@/hooks/useColors';

export default function Trainers() {
  const colors = useColors(); const { data } = useGym();
  return <ScreenScroll><Header title="Trainers" subtitle="The people behind the progress" right={<Pressable onPress={() => router.push('/trainer/new')} style={[styles.add, { backgroundColor: colors.primary }]}><Feather name="plus" size={19} color={colors.primaryForeground} /></Pressable>} /><SectionTitle title={`${data.trainers.length} trainers`} />{data.trainers.map((trainer) => { const assigned = data.members.filter((member) => member.trainerId === trainer.id && !member.archived).length; return <Pressable key={trainer.id} onPress={() => undefined} style={[styles.trainer, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.secondary }]}><Text style={[styles.initials, { color: colors.secondaryForeground }]}>{trainer.name.split(' ').map((part) => part[0]).join('')}</Text></View><View style={{ flex: 1 }}><Text style={[styles.name, { color: colors.foreground }]}>{trainer.name}</Text><Text style={[styles.specialty, { color: colors.secondaryForeground }]}>{trainer.specialization}</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>{trainer.phone} · {assigned} assigned member{assigned === 1 ? '' : 's'}</Text></View><Feather name="chevron-right" size={17} color={colors.mutedForeground} /></Pressable>})}<View style={[styles.future, { backgroundColor: colors.secondary }]}><Feather name="award" size={18} color={colors.secondaryForeground} /><View style={{ flex: 1 }}><Text style={[styles.futureTitle, { color: colors.foreground }]}>Built for your coaching team</Text><Text style={[styles.meta, { color: colors.mutedForeground }]}>Personal training sessions, commission and performance analytics can plug into this model later.</Text></View></View></ScreenScroll>;
}
const styles = StyleSheet.create({ add: { width: 38, height: 38, borderRadius: 13, justifyContent: 'center', alignItems: 'center' }, trainer: { borderWidth: 1, borderRadius: 18, padding: 14, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 9 }, avatar: { width: 48, height: 48, borderRadius: 17, justifyContent: 'center', alignItems: 'center' }, initials: { fontFamily: 'Inter_700Bold', fontSize: 15 }, name: { fontFamily: 'Inter_700Bold', fontSize: 14 }, specialty: { fontFamily: 'Inter_600SemiBold', fontSize: 11, marginTop: 4 }, meta: { fontFamily: 'Inter_400Regular', fontSize: 10, lineHeight: 16, marginTop: 4 }, future: { borderRadius: 17, padding: 14, flexDirection: 'row', gap: 10, marginTop: 14 }, futureTitle: { fontFamily: 'Inter_700Bold', fontSize: 12, marginBottom: 3 } });